### ISSUE TITLE
Download broken

### ISSUE THREAD

**Issue by mwrsa** [Chocohead/Rift#17]
Hey there,
the link https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar leads to a missing file. I downloaded the file it's supposed to link to minus one letter in its name, but that doesn't seem to help it since I am stuck in a loop in the MC launcher now - I chose the right profile, it seems to download the rift jar, then it's back to the launcher and the play button is available again. Rinse and repeat. Any solution please? Ty.

EDIT: Rift 1.0.4-106 fails in exactly the same way.

**Comment by Chocohead** [comment]
"Fixed" in c283efe

**Comment by mwrsa** [comment]
Thanks a ton! Pls excuse the dumb question: What do I have to do now? Just relaunch the launcher and game?

Edit: I did just that, with this result in the launcher:
`OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[16:38:31] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[16:38:31] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[16:38:31] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[16:38:31] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more
`

**Another EDIT: Fail on my side. With the snapshot download it seems to work just fine. Tyvm!**

**Comment by Chocohead** [comment]
If you ever get the `ClassNotFoundException`s rerunning the installer will fix it, sometimes the launcher does silly things which causes trouble. Anything which couldn't download Rift before should work fine now if it tries again.
