### ISSUE TITLE
Linux crash 1.13.2

### ISSUE THREAD

**Issue by Efimero** [Chocohead/Rift#23]
```
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
on linux (debian), the installer runs and sets up the profile fine, but running it fails, first due to an unrecognized JVM option in the default arguments, but when fixing that, the error above shows
this only happens with the rift profile, the vanilla runs fine
this is before adding any mods on a clean profile

**Comment by Chocohead** [comment]
You need to use Java 8 to launch the game, LaunchWrapper doesn't run with 9 and onwards (as you've found).
